package main

import (
    "context"
    "encoding/json"
    "log"
    "net/http"
    "os"
    "strings"
    "sync"
    "time"
)

type State struct { mu sync.RWMutex; Policy map[string]any; Devices []map[string]any; Usage map[string]any; Rules map[string][]map[string]any; Store *SQLStore }

func main() {
    s:=&State{Policy:map[string]any{"version":1,"profile":"FAMILY","dns":map[string]any{"enabled":true,"dnssec":true,"encrypted":true,"resolver_preference":"FTN"},"resolver_policy":map[string]any{"ftn":true,"cloudflare_family":false,"public_fallback":false}},Devices:[]map[string]any{},Usage:map[string]any{"allowed":0,"blocked":0,"failed":0,"resolver":"FTN","dnssec":true,"policy_version":1},Rules:map[string][]map[string]any{"domain":[]map[string]any{},"ip":[]map[string]any{}}}
    ctx,cancel:=context.WithTimeout(context.Background(),15*time.Second);defer cancel()
    sqlStore,err:=OpenSQLStore(ctx);if err!=nil{log.Fatalf("database startup failed: %v",err)};s.Store=sqlStore;if sqlStore!=nil{defer sqlStore.Close();if p,err:=sqlStore.ActivePolicy(ctx);err!=nil{log.Fatalf("load policy: %v",err)}else if p!=nil{s.Policy=p};if d,err:=sqlStore.ListDevices(ctx);err!=nil{log.Fatalf("load devices: %v",err)}else{s.Devices=d};log.Printf("PostgreSQL persistence enabled")}else{log.Printf("PostgreSQL DSN not configured; running in development memory mode")}
    api:=http.NewServeMux();api.HandleFunc("/api/v1/family/devices",s.devices);api.HandleFunc("/api/v1/family/policies/",s.policy);api.HandleFunc("/api/v1/dns/usage",s.usage);api.HandleFunc("/api/v1/dns/domain-rules",s.rules("domain"));api.HandleFunc("/api/v1/dns/ip-rules",s.rules("ip"));api.HandleFunc("/api/v1/family/profiles",s.profiles);api.HandleFunc("/api/v1/dns/health",s.dnsHealth);api.HandleFunc("/api/v1/providers",s.providers);api.HandleFunc("/api/v1/health/summary",s.summary);api.HandleFunc("/api/v1/family/android/enroll",s.enroll)
    root:=http.NewServeMux();root.HandleFunc("/healthz",health);root.Handle("/api/",requireAPIAuth(api));root.Handle("/",http.FileServer(http.Dir("../../web")))
    addr:=os.Getenv("FTN_FAMILY_GUARD_ADDR");if addr==""{addr=":8095"};srv:=&http.Server{Addr:addr,Handler=cors(root),ReadHeaderTimeout:5*time.Second,ReadTimeout:15*time.Second,WriteTimeout:15*time.Second,IdleTimeout:60*time.Second};log.Printf("FTN Family Guard backend listening on %s",addr);log.Fatal(srv.ListenAndServe())
}
func health(w http.ResponseWriter,_ *http.Request){write(w,map[string]any{"service":"ftn-family-guard","status":"ok","time":time.Now().UTC()})}
func(s *State)devices(w http.ResponseWriter,r *http.Request){if r.Method!=http.MethodGet{method(w);return};if s.Store!=nil{ctx,c:=requestContext(r);defer c();d,err:=s.Store.ListDevices(ctx);if err!=nil{http.Error(w,"database error",500);return};write(w,d);return};s.mu.RLock();defer s.mu.RUnlock();write(w,s.Devices)}
func(s *State)policy(w http.ResponseWriter,r *http.Request){switch r.Method{case http.MethodGet:if s.Store!=nil{ctx,c:=requestContext(r);defer c();p,err:=s.Store.ActivePolicy(ctx);if err!=nil{http.Error(w,"database error",500);return};if p!=nil{write(w,p);return}};s.mu.RLock();defer s.mu.RUnlock();write(w,s.Policy);case http.MethodPost:var n map[string]any;if err:=json.NewDecoder(http.MaxBytesReader(w,r.Body,64<<10)).Decode(&n);err!=nil{http.Error(w,"invalid json",400);return};v,ok:=n["version"].(float64);if !ok||v<1{http.Error(w,"version is required",400);return};dns,ok:=n["dns"].(map[string]any);if !ok{http.Error(w,"dns policy is required",400);return};ds,ok:=dns["dnssec"].(bool);if !ok||!ds{http.Error(w,"dnssec must remain required",400);return};if _,ok:=n["resolver_policy"];!ok{n["resolver_policy"]=map[string]any{"ftn":true,"cloudflare_family":false,"public_fallback":false}};if s.Store!=nil{ctx,c:=requestContext(r);defer c();if err:=s.Store.SavePolicy(ctx,n);err!=nil{http.Error(w,"database error",500);return}};s.mu.Lock();s.Policy=n;s.Usage["policy_version"]=v;s.mu.Unlock();write(w,n);default:method(w)}}
func(s *State)usage(w http.ResponseWriter,r *http.Request){if r.Method!=http.MethodGet{method(w);return};s.mu.RLock();defer s.mu.RUnlock();write(w,s.Usage)}
func(s *State)profiles(w http.ResponseWriter,r *http.Request){if r.Method!=http.MethodGet{method(w);return};write(w,[]map[string]any{{"id":"FAMILY","name":"Family"},{"id":"CHILD","name":"Child"},{"id":"TEEN","name":"Teen"},{"id":"CUSTOM","name":"Custom"}})}
func(s *State)dnsHealth(w http.ResponseWriter,r *http.Request){if r.Method!=http.MethodGet{method(w);return};write(w,map[string]any{"dnssec":"required","resolver":"healthy","preferred":"FTN","cloudflare_family":"available-by-policy","latency_ms":0,"checked_at":time.Now().UTC()})}
func(s *State)providers(w http.ResponseWriter,r *http.Request){if r.Method!=http.MethodGet{method(w);return};write(w,[]map[string]any{{"id":"ftn","available":true,"enabled_by_default":true,"health":"healthy"},{"id":"cloudflare-family","available":true,"enabled_by_default":false,"policy_controlled":true,"health":"available-by-policy"}})}
func(s *State)summary(w http.ResponseWriter,r *http.Request){if r.Method!=http.MethodGet{method(w);return};write(w,map[string]any{"backend":"healthy","dns":"healthy","dnssec":"required","resolver":"FTN-preferred","cloudflare_family":"available-by-policy","realtime":"ready","android":"ready"})}
func(s *State)enroll(w http.ResponseWriter,r *http.Request){if r.Method!=http.MethodPost{method(w);return};var q map[string]any;if err:=json.NewDecoder(http.MaxBytesReader(w,r.Body,32<<10)).Decode(&q);err!=nil{http.Error(w,"invalid json",400);return};id,_:=q["device_id"].(string);id=strings.TrimSpace(id);if id==""{http.Error(w,"device_id is required",400);return};d:=map[string]any{"id":id,"name":"Android Device","profile":"FAMILY","status":"online","policy_version":s.Policy["version"]};if s.Store!=nil{ctx,c:=requestContext(r);defer c();if err:=s.Store.UpsertDevice(ctx,d);err!=nil{http.Error(w,"database error",500);return};write(w,map[string]any{"status":"accepted","device_id":id,"policy_version":s.Policy["version"]});return};s.mu.Lock();defer s.mu.Unlock();for _,old:=range s.Devices{if old["id"]==id{write(w,map[string]any{"status":"already-enrolled","device_id":id,"policy_version":s.Policy["version"]});return}};s.Devices=append(s.Devices,d);write(w,map[string]any{"status":"accepted","device_id":id,"policy_version":s.Policy["version"]})}
func(s *State)rules(k string)http.HandlerFunc{return func(w http.ResponseWriter,r *http.Request){switch r.Method{case http.MethodGet:if s.Store!=nil{ctx,c:=requestContext(r);defer c();v,err:=s.Store.ListRules(ctx,k);if err!=nil{http.Error(w,"database error",500);return};write(w,v);return};s.mu.RLock();defer s.mu.RUnlock();write(w,s.Rules[k]);case http.MethodPost:var v map[string]any;if err:=json.NewDecoder(http.MaxBytesReader(w,r.Body,16<<10)).Decode(&v);err!=nil{http.Error(w,"invalid json",400);return};x,ok:=v["value"].(string);if !ok||strings.TrimSpace(x)==""{http.Error(w,"value is required",400);return};a,ok:=v["action"].(string);if !ok||(a!="allow"&&a!="block"){http.Error(w,"action must be allow or block",400);return};v["value"]=strings.TrimSpace(x);if s.Store!=nil{ctx,c:=requestContext(r);defer c();if err:=s.Store.AddRule(ctx,k,v);err!=nil{http.Error(w,"database error",500);return};write(w,v);return};s.mu.Lock();s.Rules[k]=append(s.Rules[k],v);s.mu.Unlock();write(w,v);default:method(w)}}}
func requestContext(r *http.Request)(context.Context,context.CancelFunc){return context.WithTimeout(r.Context(),5*time.Second)}
func cors(next http.Handler)http.Handler{return http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){o:=os.Getenv("FTN_FAMILY_GUARD_ALLOWED_ORIGIN");if o==""{o="*"};w.Header().Set("Access-Control-Allow-Origin",o);w.Header().Set("Vary","Origin");w.Header().Set("Access-Control-Allow-Headers","Content-Type,Authorization,Idempotency-Key");w.Header().Set("Access-Control-Allow-Methods","GET,POST,OPTIONS");if r.Method==http.MethodOptions{w.WriteHeader(204);return};next.ServeHTTP(w,r)})}
func method(w http.ResponseWriter){http.Error(w,"method not allowed",405)}
func write(w http.ResponseWriter,v any){w.Header().Set("Content-Type","application/json");_ = json.NewEncoder(w).Encode(v)}
