const API=window.FTN_API||'/api/v1';const $=s=>document.querySelector(s);const app=$('#app');
const pages={overview:'Overview',devices:'Devices',dns:'DNS & DNSSEC',rules:'Rules',profiles:'Family Profiles',resolvers:'Resolvers',health:'Health',git:'Git Center',settings:'Settings'};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function card(label,value,extra=''){return `<div class="card"><div class="label">${esc(label)}</div><div class="value">${esc(value)}</div>${extra?`<div class="label">${esc(extra)}</div>`:''}</div>`}
async function get(path,fallback){try{const r=await fetch(path.startsWith('/api/v1/git/')?path:API+path);if(!r.ok)throw 0;return await r.json()}catch{return fallback}}
async function post(path,body){const r=await fetch(path.startsWith('/api/v1/git/')?path:API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json()}
async function render(page){$('#title').textContent=pages[page];
if(page==='git'){const x=await get('/api/v1/git/services',{services:[],policy:{}}),h=await get('/api/v1/git/health',{services:[]});const hs=Object.fromEntries((h.services||[]).map(v=>[v.id,v]));app.innerHTML=`<div class="grid">${card('Repositories',(x.services||[]).length)}${card('Registered nodes',new Set((x.services||[]).map(v=>v.node)).size)}${card('Deploy','Approval required')}${card('Rollback','Approval required')}</div><div class="card wide"><div class="row"><b>Git Services</b><span class="pill">Registered only</span></div><table class="table"><tr><th>Repository</th><th>Branch</th><th>Node</th><th>Service</th><th>Health</th><th>Actions</th></tr>${(x.services||[]).map(v=>{const q=hs[v.id]||{};return `<tr><td>${esc(v.repository)}</td><td>${esc(v.branch)}</td><td>${esc(v.node)}</td><td>${esc(v.service)}</td><td class="${q.status==='healthy'?'ok':''}">${esc(q.status||'unknown')} ${q.head?`· ${esc(q.head)}`:''}</td><td><button class="action" data-git="sync" data-id="${esc(v.id)}">Sync</button> <button class="action" data-git="build" data-id="${esc(v.id)}">Build</button> <button class="action" data-git="deploy" data-id="${esc(v.id)}">Deploy</button></td></tr>`}).join('')}</table><p id="gitMsg" class="muted"></p></div>`;document.querySelectorAll('[data-git]').forEach(b=>b.onclick=async()=>{const k=b.dataset.git,id=b.dataset.id;try{let r;if(k==='deploy')r=await post('/api/v1/git/deploy',{id,approval:confirm('Record deployment approval?')?'approved':'required'});else r=await post('/api/v1/git/'+k,{id});$('#gitMsg').textContent=`${k}: ${r.status||'accepted'}`;render('git')}catch(e){$('#gitMsg').textContent=`${k}: failed`}});return}
if(page==='overview'){const[u,h,d,p]=await Promise.all([get('/dns/usage',{}),get('/dns/health',{}),get('/family/devices',[]),get('/providers',[])]);app.innerHTML=`<div class="grid">${card('Allowed',u.allowed??0)}${card('Blocked',u.blocked??0)}${card('Resolver',u.resolver||'FTN')}${card('DNSSEC',u.dnssec?'Required':'Disabled')}</div><div class="grid"><div class="card wide"><div class="row"><b>Protection status</b><span class="pill">${esc(h.resolver||'healthy')}</span></div><table class="table"><tr><th>Component</th><th>Status</th><th>Latency</th></tr><tr><td>DNS Resolver</td><td class="ok">Healthy</td><td>${h.latency_ms??0} ms</td></tr><tr><td>DNSSEC</td><td class="ok">Required</td><td>Policy required</td></tr><tr><td>Policy</td><td class="ok">Active</td><td>v${esc(u.policy_version||1)}</td></tr></table></div><div class="card wide"><div class="row"><b>Devices</b><span class="pill">${d.length} registered</span></div><table class="table"><tr><th>Device</th><th>Profile</th><th>Status</th></tr>${d.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.profile)}</td><td class="ok">${esc(x.status)}</td></tr>`).join('')}</table></div></div>`}
else if(page==='devices'){const d=await get('/family/devices',[]);app.innerHTML=`<div class="card"><div class="row"><b>Registered devices</b><button id="enroll" class="action">+ Enroll Android</button></div><table class="table"><tr><th>Device</th><th>Profile</th><th>Policy</th><th>Status</th></tr>${d.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.profile)}</td><td>v${esc(x.policy_version)}</td><td class="ok">${esc(x.status)}</td></tr>`).join('')}</table><p id="deviceMsg" class="muted"></p></div>`;$('#enroll').onclick=async()=>{try{const x=await post('/family/android/enroll',{device_id:'android-'+Date.now()});$('#deviceMsg').textContent=`Enrollment accepted: ${x.device_id}`;render('devices')}catch(e){$('#deviceMsg').textContent='Enrollment failed'}}}
else if(page==='dns'){const h=await get('/dns/health',{});app.innerHTML=`<div class="grid">${card('DNSSEC',h.dnssec||'required')}${card('Resolver',h.resolver||'healthy')}${card('Latency',(h.latency_ms??0)+' ms')}${card('FTN','Preferred')}${card('1.1.1.1 Family',h.cloudflare_family||'available-by-policy')}</div><div class="card"><b>DNS pipeline</b><p class="muted">Local policy → DNSSEC-required resolver selection → approved resolver. FTN is preferred. Cloudflare Family remains available when the active policy permits it; it is not hard-blocked.</p></div>`}
else if(page==='rules'){const[d,i]=await Promise.all([get('/dns/domain-rules',[]),get('/dns/ip-rules',[])]);app.innerHTML=`<div class="grid"><div class="card wide"><div class="row"><b>Domain rules</b><span class="pill">${d.length}</span></div><form id="domainForm"><input id="domainValue" placeholder="example.com" required><select id="domainAction"><option value="block">Block</option><option value="allow">Allow</option></select><button class="action">Add</button></form><div class="empty">${d.length?d.map(x=>`<div>${esc(x.value)} · ${esc(x.action||'rule')}</div>`).join(''):'No custom domain rules'}</div></div><div class="card wide"><div class="row"><b>IP / CIDR rules</b><span class="pill">${i.length}</span></div><form id="ipForm"><input id="ipValue" placeholder="192.0.2.0/24" required><select id="ipAction"><option value="block">Block</option><option value="allow">Allow</option></select><button class="action">Add</button></form><div class="empty">${i.length?i.map(x=>`<div>${esc(x.value)} · ${esc(x.action||'rule')}</div>`).join(''):'No custom IP rules'}</div></div></div>`;$('#domainForm').onsubmit=async e=>{e.preventDefault();await post('/dns/domain-rules',{value:$('#domainValue').value,action:$('#domainAction').value});render('rules')};$('#ipForm').onsubmit=async e=>{e.preventDefault();await post('/dns/ip-rules',{value:$('#ipValue').value,action:$('#ipAction').value});render('rules')}}
else if(page==='profiles'){const p=await get('/family/profiles',[]);app.innerHTML=`<div class="grid">${p.map(x=>`<div class="card"><b>${esc(x.name||x)}</b><p class="muted">DNS filtering · malware · phishing · schedules · device policy</p><button class="action" data-profile="${esc(x.id||x)}">Select</button></div>`).join('')}</div>`}
else if(page==='resolvers'){const p=await get('/providers',[]);app.innerHTML=`<div class="card"><table class="table"><tr><th>Resolver</th><th>Default</th><th>Health / Policy</th></tr>${p.map(x=>`<tr><td>${esc(x.id)}</td><td>${x.enabled_by_default?'Yes':'No'}</td><td>${esc(x.health)}</td></tr>`).join('')}</table><p class="muted">FTN is preferred. Cloudflare Family is available-by-policy, not blocked. DNSSEC remains required.</p></div>`}
else if(page==='health'){const x=await get('/health/summary',{});app.innerHTML=`<div class="grid">${Object.entries(x).map(([k,v])=>card(k,String(v))).join('')}</div>`}
else{app.innerHTML=`<div class="card"><b>Family Guard settings</b><div class="tabs"><button>DNSSEC: Required</button><button>Raw DNS logs: Off</button><button>Payload inspection: Off</button><button>Aggregate usage: On</button><button>FTN resolver: Preferred</button><button>1.1.1.1 Family: Policy controlled</button></div></div>`}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.page)});render('overview');